---
- name:           Cleanup Binaries directory
  file:           path={{ __tmp_dir }} state=absent
  ignore_errors:  true

- name:           Create Binaries directory
  file:           path={{ __tmp_dir }} state=directory mode=0755

- name:           Create Logs directory
  file:           path={{ __logs_dir }} state=directory mode=0755

- name:           Download Domino Hot Fix
  get_url:
    url:          "{{ __repository_url }}/{{ __bin_file }}"
    dest:         "{{ __tmp_dir }}/{{ __bin_file }}"
    mode:         0755
    checksum:     sha256:{{ __bin_file_sha256 }}

- name:           Extract Domino Hot Fix
  unarchive:
    src:          "{{ __tmp_dir }}/{{ __bin_file }}"
    dest:         "{{ __tmp_dir }}/"
    copy:         no
    creates:      "{{ __tmp_dir }}/{{ __os }}/install"

- name:           Generate Domino HF Install Response file
  template:
    src:          domino_hf_install.rsp.j2
    dest:         "{{ __rsp_file }}"

- name:           Install IBM Domino Hot Fix
  shell:
    "{{ __tmp_dir }}/{{ __os }}/install -script {{ __rsp_file }}"
  args:
    chdir:        "{{ __tmp_dir }}/{{ __os }}"
  environment:
    NUI_NOTESDIR: "{{ __dom_install_location }}"
  register:       cout
  changed_when:   ( cout.stdout.find('The installation completed successfully') != -1 )

- name:           "Write log to file "
  copy:
    content:      "{{ cout.stdout }}"
    dest:         "{{ __log_file }}"

- name:           Cleanup Binaries directory
  file:           path={{ __tmp_dir }} state=absent