---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml

#-  debug:       var=version_already_installed
# TODO:          STOP DOMINO
#- include:      domino-server-stop.yml
#  when:         version_already_installed.rc != 0

- include:       install_hf.yml
#  when:         version_already_installed.rc != 0
