---
- name:                 "Verify if pid file"
  shell:                "ps -p `cat '{{ __dom_notesdata }}/domino.pid'`"
  register:             domino_is_running
  ignore_errors:        true

#TARGET_REAL_BIN=`readlink -f $1`
#  FOUND_TARGETS=`lsof | awk '{print $9}' | grep "$TARGET_REAL_BIN"`

- name:                 "Stop Domino"
  shell:                "su - {{ __dom_user }} \"cd {{ __dom_notesdata }} & {{ __dom_install_location }}/bin/server -c 'stop task http' \" "
  register:             cout
  changed_when:         cout.rc == 0
  #changed_when:        ( start.stdout.find('open for e-business') != -1)
  when:                 domino_is_running.rc == 0

