---
- name:                 "Verify if pid file"
  shell:                "ps -p `cat '{{ __dom_notesdata }}/domino.pid'`"
  register:             domino_is_running
  ignore_errors:        true

#TARGET_REAL_BIN=`readlink -f $1`
#  FOUND_TARGETS=`lsof | awk '{print $9}' | grep "$TARGET_REAL_BIN"`

- name:                 "Stop Domino"
  command:              "service rc_domino stop"
  register:             cout
  changed_when:         cout.rc == 0
  #changed_when:        ( start.stdout.find('open for e-business') != -1)
  when:                 domino_is_running.rc == 0



#systemctl start domino.service
#systemctl stop domino.service
#systemctl status domino.service

#when:           (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS")

#RH7 CENTOS SLES12
