---
- name:                "Is First Domino Setup?"
  stat:
    path:              "{{ __dom_install_location }}"
  register:            first_time_setup


#tail "$DOMINO_INSTALL_DAT" | grep "rev = " | awk -F " = " '{print $2}' | tr -d '"'

- name:                Is Product already Installed?
  command:             "egrep 'target_version = \"' {{ __dom_install_location }}/.install.dat"
  register:            __cout
  ignore_errors:       true

- name:                Is Product already Installed 2?
  command:             "egrep 'rev = ' {{ __dom_install_location }}/.install.dat"
  register:            __cout2
  ignore_errors:       true
  when:                __cout.rc == 1

- name:                Install Domino 10.0.1?
  set_fact:
    __bin_file:        "DOM_SVR_V10.0.1_64_BIT_Lnx.tar"
    __bin_file_sha256: "57a19f56da492740d50457bcb3eec6f2b5410e8e122608c19e1886cf3fb36515"
  when:                ( __this_version == '10.0.1' )

- name:                Install Domino 9.0.1?
  set_fact:
    __bin_file:        "DOMINO_9.0.1_64_BIT_LIN_XS_EN.tar"
    __bin_file_sha256: "9f5f941ec43ca268197cb1250a2677630789a4efeca73d38d69ebecd7d32870a"
  when:                ( __this_version == '9.0.1' )

# return code 0 when string found
#TODO:                 Change this for Domino v10
- set_fact:
    __release_str:     "{{ __cout2.stdout | regex_replace('.*(\\d3)\\d2.*','\\1')  }}"
  when:                (__cout.rc == 1) and (__cout2.rc == 0)

- set_fact:
    __release_str:     "{{ __cout.stdout | regex_replace('.*\"(\\d*)FP.*','\\1')  }}"
    __fp_str:          "{{ __cout.stdout | regex_replace('.*FP(\\d*).*','\\1')  }}"
  when:                __cout.stdout is search("FP")

- set_fact:
    __hf_str:          "{{ __cout.stdout | regex_replace('.*HF(\\d*)\".*','\\1')  }}"
  when:                __cout.stdout is search("HF")

#TODO:                 Ansible not convert to int because Jinja2
- set_fact:
    __release:         "{{ __release_str | int }}"
    __fp:              "{{ __fp_str | int }}"
    __hf:              "{{ __hf_str | int }}"


- debug:               var=__release
- debug:               var=__fp
- debug:               var=__hf

- debug:               var=__cout
- debug:               var=__cout2


- debug:               var=__this_version[0:3]
