---
- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
  ignore_errors: true

- name:          Create Binaries directory
  file:          path={{ __tmp_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __logs_dir }} state=directory mode=0755

- name:          Download IBM Domino
  get_url:
    url:         "{{ __repository_url }}/{{ __bin_file }}"
    dest:        "{{ __tmp_dir }}/{{ __bin_file }}"
    mode:        0755
    checksum:    sha256:{{ __bin_file_sha256 }}

- name:          Extract IBM Domino
  unarchive:
    src:         "{{ __tmp_dir }}/{{ __bin_file }}"
    dest:        "{{ __tmp_dir }}/"
    copy:        no
    creates:     "{{ __tmp_dir }}/{{ __os }}/domino/install"

- name:          Generate Domino Install Response file
  template:
    src:         domino_install.rsp.j2
    dest:        "{{ __rsp_file }}"

- name:          "Install IBM Domino Software -- This takes a while ..."
  shell:
    "{{ __tmp_dir }}/{{ __os }}/domino/install -silent -options {{ __rsp_file }}"
  args:
    chdir:       "{{ __tmp_dir }}/{{ __os }}/domino"
    creates:     "{{ __dom_install_location }}/bin/server"
  
- name:          "Verify Installation"
  shell:
    "egrep 'Dominoserver Installation successful' {{ __domino_exec_directory }}/DominoInstall.log"
  register:      cout
  changed_when: (cout.rc == 0)
  ignore_errors: true

- name:          "Move DominoInstall.log to log directory"
  shell:
    "mv {{ __domino_exec_directory }}/DominoInstall.log {{ __logs_dir }}/."
  ignore_errors: true

- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
