---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml

- name:          Define Domino Versions
  include_tasks: define_versions.yml

- name:          Setup OS
  include_tasks: setup_os.yml
  when:          ( __new_install == true )

#- include:      domino-server-stop
#  when:          first_time_setup.stat.exists != true
#  when:         __release < __this_version[0:3]

- name: Print some debug information 
  vars: 
    msg: |
        __curr_ver: {{ __curr_ver }}
        __curr_fp: {{ __curr_fp }}
        __curr_hf: {{ __curr_hf }}
        __bin_version: {{ __bin_version }}
        __bin_fp_version: {{ __bin_fp_version }}
        __bin_hf_version: {{ __bin_hf_version }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info
  when: ( __debug_enabled == true )

- include:       install_domino.yml
  when:          ( __curr_ver|int < __bin_version )

