# check_vars.yml
---
- name: traveler_repository_url should be defined
  assert:
    that:
    - traveler_repository_url is defined and traveler_repository_url != ''
    msg: "Set the value of 'traveler_repository_url' in the inventory file."
