---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml
  
#- include:       domino-server-stop.yml
#  when:          version_already_installed.rc != 0

- include:       inst-domino-lp.yml
  when:          version_already_installed.rc != 0

#- include:       domino-server-start.yml
#  when:          version_already_installed.rc != 0
