# check_vars.yml
---
- name: verse_repository_url should be defined
  assert:
    that:
    - verse_repository_url is defined and verse_repository_url != ''
    msg: "Set the value of 'verse_repository_url' in the inventory file."
