---
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Define Vars
  include_tasks: define_vars.yml

- name:          Define Domino Versions
  include_tasks: define_versions.yml

- include:       install_verse.yml
  #when:          ( __curr_ver|int == __bin_version ) and ( __curr_fp|int == __bin_fp_version ) and ( __curr_hf|int < __bin_hf_version )
