---
__repository_url:       "{{ domino_lp_repository_url }}"
__tmp_dir:              "{{ tmp_dir | default('/opt/Binaries') }}/domino_lp"
__logs_dir:             "{{ tmp_dir | default('/opt/Binaries') }}/logs"

__dom_install_location: "{{ domino_install_location | default('/opt/ibm/domino') }}"
__dom_notesdata:        "{{ domino_notesdata | default('/domino/notesdata') }}"
__dom_user:             "{{ domino_user      | default('notes') }}"
__dom_group:            "{{ domino_group     | default('notes') }}"

__lp_version:         "{{ domino_lp_version | default('9.0.1') }}"

__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/domino_lp_install.rsp"
__log_file:             "{{ __logs_dir }}/domino_lp_install.{{ __now }}.log"
__tpl_file:             "domino_lp_install.rsp.j2"

__language:             "pt_br"
