---
__repository_url:        "{{ domino_hf_repository_url }}"
__tmp_dir:               "{{ tmp_dir | default('/opt/Binaries') }}/domino_hf"
__logs_dir:              "{{ tmp_dir | default('/opt/Binaries') }}/logs"

__dom_install_location:  "{{ domino_install_location | default('/opt/ibm/domino') }}"
__dom_notesdata:         "{{ domino_notesdata | default('/domino/notesdata') }}"
__dom_user:              "{{ domino_user      | default('notes') }}"
__dom_group:             "{{ domino_group     | default('notes') }}"

__domino_version:        "{{ domino_version | default('10.0.1') }}"
__domino_fp_version:     "{{ domino_fp | default('FP2') }}"
__domino_hf_version:     "{{ domino_hf | default('HF32') }}"

__now:                   "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:              "{{ __logs_dir }}/domino_hf_install.rsp"
__log_file:              "{{ __logs_dir }}/domino_hf_install.{{ __now }}.log"
__os:                    "{{ ansible_system | lower }}64"
__os_noarch:             "{{ ansible_system | lower }}"

__curr_ver:             "0"
__curr_fp:              "0"
__curr_hf:              "0"
__new_install:          true

__debug_enabled:        true