---
__repository_url:        "{{ domino_fp_repository_url }}"
__tmp_dir:               "{{ tmp_dir | default('/opt/Binaries') }}/domino_fp"
__logs_dir:              "{{ tmp_dir | default('/opt/Binaries') }}/logs"

__dom_install_location:  "{{ domino_install_location | default('/opt/ibm/domino') }}"
__dom_notesdata:         "{{ domino_notesdata | default('/domino/notesdata') }}"
__dom_user:              "{{ domino_user      | default('notes') }}"
__dom_group:             "{{ domino_group     | default('notes') }}"

__bin_file:              "{{ domino_fp_bin_file | default('DOM_SVR_V10.0.1_FP1_64B_LINUX_EN.tar') }}"
__bin_file_sha256:       "{{ domino_fp_bin_file_sha256 | default('6f6209bd14814001d52cc3b0af734a3ead119e9f4e97341bf2ebaa3505550aa8') }}"
__this_version:          "{{ domino_fp_version | default('10.0.1FP1') }}"

__now:                   "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:              "{{ __logs_dir }}/domino_fp_install.rsp"
__log_file:              "{{ __logs_dir }}/domino_fp_install.{{ __now }}.log"
__tpl_file:              "domino_fp_install.rsp.j2"
__os:                    "{{ ansible_system | lower }}64"
