---
- name:            Is Product already Installed?
  command:         "egrep 'target_version = \"' {{ __dom_install_location }}/.install.dat"
  register:        __cout
  ignore_errors:   true

- name:            Is Product already Installed 2?
  command:         "egrep 'rev = ' {{ __dom_install_location }}/.install.dat"
  register:        __cout2
  ignore_errors:   true
  when:            __cout.rc == 1

# return code 0 when string found
#TODO:             Change this for Domino v10
- set_fact:
    __release_str: "{{ __cout2.stdout | regex_replace('.*(\\d3)\\d2.*','\\1')  }}"
  when:            (__cout.rc == 1) and (__cout2.rc == 0)

- set_fact:
    __release_str: "{{ __cout.stdout | regex_replace('.*\"(\\d*)FP.*','\\1')  }}"
    __fp_str:      "{{ __cout.stdout | regex_replace('.*FP(\\d*).*','\\1')  }}"
  when:            __cout.stdout is search("FP")

- set_fact:
    __hf_str:      "{{ __cout.stdout | regex_replace('.*HF(\\d*)\".*','\\1')  }}"
  when:            __cout.stdout is search("HF")

#TODO:             Ansible not convert to int because Jinja2
- set_fact:
    __release:     "{{ __release_str | int }}"
    __fp:          "{{ __fp_str | int }}"
    __hf:          "{{ __hf_str | int }}"


- debug:           var=__release
- debug:           var=__fp
- debug:           var=__hf

- debug:           var=__cout
- debug:           var=__cout2


- debug:           var=__this_version[0:3]
