# check_vars.yml
---
- name: domino_fp_repository_url should be defined
  assert:
    that:
    - domino_fp_repository_url is defined and domino_fp_repository_url != ''
    msg: "Set the value of 'domino_fp_repository_url' in the inventory file."
