---
- name:           Cleanup Binaries directory
  file:           path={{ __tmp_dir }} state=absent
  ignore_errors:  true

- name:           Create Binaries directory
  file:           path={{ __tmp_dir }} state=directory mode=0755

- name:           Create Logs directory
  file:           path={{ __logs_dir }} state=directory mode=0755

- name:           Download Domino Fix Pack
  get_url:
    url:          "{{ __repository_url }}/{{ __bin_file }}"
    dest:         "{{ __tmp_dir }}/{{ __bin_file }}"
    mode:         0755
    checksum:     sha256:{{ __bin_file_sha256 }}

- name:           Extract Domino Fix Pack
  unarchive:
    src:          "{{ __tmp_dir }}/{{ __bin_file }}"
    dest:         "{{ __tmp_dir }}/"
    copy:         no
    creates:      "{{ __tmp_dir }}/{{ __os }}/domino/install"

- name:           "Generate Domino FP Install Response file"
  template:
    src:          "{{ __tpl_file }}"
    dest:         "{{ __rsp_file }}"

- name:           "Install IBM Domino Fix Pack -- This takes a while ..."
  shell:
    "{{ __tmp_dir }}/{{ __os }}/domino/install -script {{ __rsp_file }}"
  args:
    chdir:        "{{ __tmp_dir }}/{{ __os }}/domino"
  environment:
    NUI_NOTESDIR: "{{ __dom_install_location }}"
  register:       cout
  changed_when:   ( cout.stdout.find('The installation completed successfully') != -1 )

- name:           "Write log to file "
  copy:
    content:      "{{ cout.stdout }}"
    dest:         "{{ __log_file }}"

- name:           Cleanup Binaries directory
  file:           path={{ __tmp_dir }} state=absent
