---
__tmp_dir:               "{{ tmp_dir | default('/opt/Binaries') }}/domino"
__logs_dir:              "{{ tmp_dir | default('/opt/Binaries') }}/logs"

__dom_install_location:  "{{ domino_install_location | default('/opt/ibm/domino') }}"
__dom_notesdata:         "{{ domino_notesdata | default('/domino/notesdata') }}"
__dom_user:              "{{ domino_user      | default('notes') }}"
__dom_group:             "{{ domino_group     | default('notes') }}"


